/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicIntakeSubmitRouteImport } from './routes/api/public/intake-submit'
import { Route as ApiPublicContactRouteImport } from './routes/api/public/contact'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIntakeSubmitRoute = ApiPublicIntakeSubmitRouteImport.update({
  id: '/api/public/intake-submit',
  path: '/api/public/intake-submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContactRoute = ApiPublicContactRouteImport.update({
  id: '/api/public/contact',
  path: '/api/public/contact',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/intake-submit': typeof ApiPublicIntakeSubmitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/intake-submit': typeof ApiPublicIntakeSubmitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/intake-submit': typeof ApiPublicIntakeSubmitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/contact' | '/api/public/intake-submit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/contact' | '/api/public/intake-submit'
  id: '__root__' | '/' | '/api/public/contact' | '/api/public/intake-submit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicContactRoute: typeof ApiPublicContactRoute
  ApiPublicIntakeSubmitRoute: typeof ApiPublicIntakeSubmitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/intake-submit': {
      id: '/api/public/intake-submit'
      path: '/api/public/intake-submit'
      fullPath: '/api/public/intake-submit'
      preLoaderRoute: typeof ApiPublicIntakeSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contact': {
      id: '/api/public/contact'
      path: '/api/public/contact'
      fullPath: '/api/public/contact'
      preLoaderRoute: typeof ApiPublicContactRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicContactRoute: ApiPublicContactRoute,
  ApiPublicIntakeSubmitRoute: ApiPublicIntakeSubmitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
